# Crash Information
AppName: Crusader Kings III 
AppVersion: 1.12.5 
SCMBranch: release/1.12.5 
SCMCommit: 40aeab7abc09fdd23d847eb31a8cc5ec9732d072 
SCMTimeStamp: "2024-04-29 16:52:00 +0200" 
DateTime: "2024-05-13 13:13:00 +0800" 
BuildType: ReleaseLto 
Platform: Windows 
Store: steam 
Architecture: 64-bit 
OperatingSystem: Windows 10 x86_64 
SystemLanguage: zh 
CPUModel:       Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz 
CPUSpeed: 2494 
CPUPhysicalCores: 10 
CPULogicalCores: 20 
SystemMemory: 32688 
GPUName: NVIDIA GeForce GTX 1080 
GPUVendor: nVidia 
GPUId: 7040 
GPUDedicatedMemory: 8059 
LaunchArguments: --continuelastsave --gdpr-compliant --nakama --paradox-account-userid="" --pdx-launcher-session-token="" --simultaneouschunks="" 
