# Crash Information
AppName: Victoria 3 
AppVersion: 1.7.0 
SCMBranch: release/1.7.day0 
SCMCommit: 1cc643970a8110675d729e02b6f05ed09431f7c2 
SCMTimeStamp: "2024-06-14 15:41:33 +0000" 
DateTime: "2024-06-26 21:47:19 +0800" 
BuildType: ReleaseLto 
Platform: Windows 
Store: steam 
Architecture: 64-bit 
OperatingSystem: Windows 10 x86_64 
SystemLanguage: zh 
CPUModel:       Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz 
CPUSpeed: 2494 
CPUPhysicalCores: 10 
CPULogicalCores: 20 
SystemMemory: 32688 
GPUName: NVIDIA GeForce GTX 1080 
GPUVendor: nVidia 
GPUId: 7040 
GPUDedicatedMemory: 8059 
LaunchArguments: --continuelastsave --gdprcompliant --paradoxaccountuserid="" --pdxlaunchersessiontoken="" --pdxllauncherinvokedtimestamp="" 
DLC_1: Voice of the People Preorder 
DLC_2: Region Pack 1 
DLC_3: Free Trains Pack 
DLC_4: Sphere of Influence 
DLC_5: Dawn of Wonder 
DLC_6: Voice of the People 
DLC_7: Victoria 2 Remastered Soundtrack 
DLC_8: American Buildings Pack 
DLC_9: Melodies for the Masses 
Mod_1: Infinite Resources Buildings with Investment Pool 
Mod_2: Restrict Autonomous Investment 
Mod_3: Luxury Goods Factories 
Mod_4: Daoyu Cheat - Achievement Available Cheat Tool 
Mod_5: No local product 
Mod_6: Cheat Buildings 
