# Crash Information
AppName: Victoria 3 
AppVersion: 1.7.0 
SCMBranch: release/1.7.day0 
SCMCommit: 1cc643970a8110675d729e02b6f05ed09431f7c2 
SCMTimeStamp: "2024-06-14 15:41:33 +0000" 
DateTime: "2024-06-26 19:37:28 +0800" 
BuildType: ReleaseLto 
Platform: Windows 
Store: steam 
Architecture: 64-bit 
OperatingSystem: Windows 10 x86_64 
SystemLanguage: zh 
CPUModel:       Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz 
CPUSpeed: 2494 
CPUPhysicalCores: 10 
CPULogicalCores: 20 
SystemMemory: 32688 
GPUName: NVIDIA GeForce GTX 1080 
GPUVendor: nVidia 
GPUId: 7040 
GPUDedicatedMemory: 8059 
LaunchArguments: --gdprcompliant --paradoxaccountuserid="" --pdxlaunchersessiontoken="" --pdxllauncherinvokedtimestamp="" 
DLC_1: Voice of the People Preorder 
DLC_2: Region Pack 1 
DLC_3: Free Trains Pack 
DLC_4: Sphere of Influence 
DLC_5: Dawn of Wonder 
DLC_6: Voice of the People 
DLC_7: Victoria 2 Remastered Soundtrack 
DLC_8: American Buildings Pack 
DLC_9: Melodies for the Masses 
Mod_1: Chinese Super League 
Mod_2: Infinite Resources Buildings with Investment Pool 
Mod_3: Luxury Goods Factories 
Mod_4: Daoyu Cheat - Achievement Available Cheat Tool 
Mod_5: No local product 
Mod_6: transportation not local 
Mod_7: Enhanced Autonomous Investment 
Mod_8: Chinese lanuague for Advanced Cheat Menu 
Mod_9: Treasury to Investment Pool 
Mod_10: Cheat Buildings 
Mod_11: Military Logistics and Stockpiles 
Mod_12: 300 Construction Max per week 
Mod_13: Make My Railway Profitable Again! 
Mod_14: [on-off] Autonomous Investment Pool 
Mod_15: Upgrade All Units 
Mod_16: 污染处理设施 
Mod_17: Give all Achievements 
Mod_18: 种植园运输方式新增 
Mod_19: Doodles War Flags & Flag Tweaks 
Mod_20: Land development 
Mod_21: Trade electricity 
